config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/sign_up',  to: 'users#new'
  resources :users, only: [:show, :edit, :create, :update, :destroy]
  resources :reservations, only: [:new, :index, :create]
  resources :rooms, only: [:new, :index, :show, :create] do
    collection do
      get :search
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
  scope :recent, -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :room_name, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :address, presence: true
  validates :image, attached: true, content_type: { in: ['image/jpeg', 'image/jpg', 'image/png'],
                                                         message: "は以下のファイル形式で入力してください  .jpeg .jpg .png" },
                                     size:        { less_than: 5.megabytes, message: "の容量が5MBを超えています" }

  class << self
    def look_area(area)
      where("address LIKE?", "%#{area}%")
    end

    def look_word(word)
      where("room_name LIKE? OR introduction LIKE?", "%#{word}%", "%#{word}%")
    end
  end

  def image_resize
    image.variant(resize: '1000x600')
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @room = Room.new
  end

  def index
    @pagy, @rooms = pagy(current_user.rooms.recent)
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def search
    if params[:area]
      @pagy, @rooms = pagy(Room.look_area(params[:area]).recent)
    elsif params[:word]
      @pagy, @rooms = pagy(Room.look_word(params[:word]).recent)
    else
      redirect_to root_url
    end
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = "ルーム情報を登録しました"
      redirect_to @room
    else
      render 'new'
    end
  end

  private
    def room_params
      params.require(:room).permit(:room_name, :introduction, :price, :address, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<tr>
  <td><%= link_to image_tag(room.image_resize, alt: "ルーム画像", class: "index-image"), room_path(room) %></td>
  <td><%= link_to(room.room_name, room_path(room)) %></td>
  <td><%= room.introduction %></td>
  <td>¥<%= room.price %></td>
  <td><%= room.created_at.to_s(:datetime_jp) %></td>
</tr>

app/views/rooms/_search_rooms.html.erb
<div class="col-xl-3 col-lg-4 col-6">
  <div class="room-container">
    <a href=<%= room_url(room) %> >
      <div>
        <%= image_tag room.image_resize, class: "room-image" %>
      </div>
      <div class="room-about">
        <p><%= room.room_name %></p>
        <p><%= room.address %></p>
        <p>¥<%= room.price %></p>
      </div>
    </a>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container index-container">
  <h1>登録済みルーム一覧</h1>
  <table class="table">
    <thead class="index-thead">
      <tr>
        <th scope="col">ルーム画像</th>
        <th scope="col">ルーム名</th>
        <th scope="col">ルーム紹介</th>
        <th scope="col">料金</th>
        <th scope="col">作成日</th>
      </tr>
    </thead>
    <tbody class="index-tbody">
      <%= render @rooms %>
    </tbody>
  </table>
</div>

<%= render 'shared/pagy' %>

app/views/rooms/new.html.erb
<div class="container-fluid room-form">
  <div class="room-form-inner">
    <h1>ルーム情報登録</h1>
    <%= form_with(model:@room, local: true) do |f| %>
      <div class="container">
        <%= render 'shared/error_messages', object:f.object %>

        <div class="row room-content">
          <div class="col-3">
            <%= f.label :room_name, class: "form-label" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.text_field :room_name, placeholder:"ルーム名を入力", class: "form-control" %>
          </div>
        </div>

        <div class="row room-content">
          <div class="col-3">
            <%= f.label :introduction, class: "form-label" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.text_area :introduction, placeholder:"ルーム説明を入力", class: "form-control" %>
          </div>
        </div>

        <div class="row room-content">
          <div class="col-3">
            <%= f.label :price, class: "form-label" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.number_field :price, placeholder:"一日あたりの料金を入力", class: "form-control" %>
          </div>
        </div>

        <div class="row room-content">
          <div class="col-3">
            <%= f.label :address, class: "form-label" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.text_field :address, placeholder:"住所を入力", class: "form-control" %>
          </div>
        </div>

        <div class="row room-content">
          <div class="col-3">
            <%= f.label :image, class: "form-label" %>
            <span class="badge bg-danger">必須</span>
          </div>
          <div class="col-9">
            <%= f.file_field :image, class: "form-control" %>
          </div>
        </div>

        <%= f.submit "登録", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="container room-index">
  <p class="search-count"><%= "検索結果: #{@pagy.count}件中#{@rooms.count}件を表示" %></p>
  <div class="row">
    <%= render partial: 'search_rooms', collection: @rooms, as: :room %>
  </div>
</div>

<%= render 'shared/pagy' %>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md-8 room-show-inner">
      <%= image_tag @room.image.variant(resize: '1000x600'), class: "room-image" %>
      <div class="room-profile">
        <p><%= @room.room_name %></p>
        <p><%= @room.address %></p>
      </div>
      <p><%= @room.introduction %></p>
    </div>
    <div class="col-md-4 reservation-field">
      <div class="reservation-field-inner">
        <p>¥ <%= @room.price %> / 日</p>
        <%= form_with(model: @reservation, url: new_reservation_path, method: :get, local: true) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= hidden_field_tag :id, @room.id %>

          <%= f.label :start_date, class: "form-label" %>
          <%= f.date_field :start_date, class: "form-control" %>

          <%= f.label :end_date, class: "form-label" %>
          <%= f.date_field :end_date, class: "form-control" %>

          <%= f.label :sum_people, class: "form-label" %>
          <%= f.number_field :sum_people, class: "form-control" %>

          <%= f.submit "確認画面に進む", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>