config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/sign_up',  to: 'users#new'
  resources :users, only: [:show, :edit, :create, :update, :destroy]
  resources :reservations, only: [:new, :index, :create]
  resources :rooms, only: [:new, :index, :show, :create] do
    collection do
      get :search
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; 2020 POTEPAN INC.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-dark">
  <div class="container-fluid">
    <div class="navbar navbar-light">
      <div class="navbar">
        <div class="nav-item">
          <%= link_to image_tag("logo.png", alt: "ロゴ"), root_url %>
        </div>
        <div class="nav-item form-area">
          <%= form_with(url: search_rooms_path, method: :get, local: true) do |f| %>
            <%= f.text_field :area, placeholder: " エリア", class: "form-control" %>
          <% end %>
        </div>
        <div class="nav-item form-area">
          <%= form_with(url: search_rooms_path, method: :get, local: true) do |f| %>
            <%= f.text_field :word, placeholder: "キーワード", class: "form-control" %>
          <% end %>
        </div>
      </div>
      <% if logged_in? %>
        <div class="navbar d-flex">
          <div class="nav-item me-2">
            <%= link_to image_tag(current_user.image_user_resize, alt: "ユーザーアイコン", class: "user-image"), user_path(current_user) %>
          </div>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              メニュー
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
              <li><%= link_to "ルーム登録", new_room_path, class: "dropdown-item" %></li>
              <li><%= link_to "予約済みルーム一覧", reservations_path, class: "dropdown-item" %></li>
              <li><%= link_to "登録済みルーム一覧", rooms_path, class: "dropdown-item" %></li>
              <li><%= link_to "アカウント設定", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="nav-item">
          <%= link_to "ログイン", login_path, class: "btn btn-primary" %>
          <%= link_to "登録する", sign_up_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shukuhaku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type} alert-bottom") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>